CREATE DATABASE BankAPI;

CREATE TABLE IF NOT EXISTS Users (
	cpf TEXT NOT NULL,
	full_name TEXT NOT NULL,
	password TEXT NOT NULL,
	PRIMARY KEY (cpf)
);

CREATE TABLE IF NOT EXISTS Transactions (
	id SERIAL,
	user_cpf TEXT NOT NULL,
	transaction_type TEXT NOT NULL,
	date DATE NOT NULL DEFAULT CURRENT_DATE,
	PRIMARY KEY (id)
);